version: "3.6"

services:

  # backend api
  smart-brain-api:
    container_name: backend
    # image: node:14.17.6
    build:
      context: ./
      dockerfile: dockerfile
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_URI: postgres://sally:secret@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/smart-brain-api
    # command: npm start
    stdin_open: true
    tty: true

  # postgres
  postgres:
    # no need
    # container_name: postgres
    # image: postgres
    build: ./postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres

  # redis
  redis:
    # no need
    # container_name: cache
    image: redis
    ports:
      - "6379:6379"